name: GitHub README

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README Profile
    steps:
      - uses: actions/checkout@v2
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update README"
          git push
          fi
