name: GitHub README

on:
  schedule:
    - cron: '0 0/12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README Profile
    steps:
      - uses: actions/checkout@v2
      - name: Update README Waka stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO : "False"
          SHOW_LINES_OF_CODE : "False"
          SHOW_PROFILE_VIEWS : "True"
          SHOW_OS : "False"
          SHOW_EDITORS : "True"
          SHOW_PROJECTS : "True"
          SHOW_LANGUAGE : "True"
          SHOW_TIMEZONE : "True"
          SHOW_LOC_CHART : "False"
          SHOW_LANGUAGE_PER_REPO : "True"
